//>>built
define("esri/dijit/metadata/editor/PrimaryToolbarMixin","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-class dojo/dom-style dojo/has dojo/i18n!../nls/i18nBase ../base/ValidationTracker ../base/xml/XmlInterrogator ../base/xml/xmlUtil ./util/DownloadXmlDialog ./util/LoadDocumentDialog ./util/MessageDialog ./util/SaveDocumentDialog ./util/TransformDialog ../base/transform/Iso2IsoTransformer ../../../kernel".split(" "),function(k,c,t,n,r,u,d,l,v,p,w,x,h,y,z,A,B){k=k(null,{constructor:function(b){c.mixin(this,
b)},_compareXmls:function(b,a){var g=function(a){if("undefined"===typeof a||null===a)return a;var b=a.indexOf("\x3cModTime\x3e"),c;return-1!==b&&(c=a.indexOf("\x3c/ModTime\x3e"),c>b)?(b=a.substring(0,b),a=a.substring(c+10),b+a):a},c=g(b),g=g(a);return c===g?!0:!1},_confirmAndDelete:function(){if(this.editor.gxeAdaptor.getAllowEditMetadata()&&this.editor.gxeAdaptor.getAllowDeleteMetadata()){var b=this.editor&&this.editor.dialogBroker;(new h({title:d.editor.del.dialogTitle,okLabel:d.editor.del.caption,
onOkClick:c.hitch(this,function(){var a=new h({title:d.editor.del.dialogTitle,showOkCancelBar:!1});a.show(d.editor.del.working).then(c.hitch(this,function(){this.editor.gxeAdaptor.deleteMetadata({}).then(c.hitch(this,function(){this.lastSavedXml=null;setTimeout(c.hitch(this,function(){a.hide();b&&this._close()}),1500)}),c.hitch(this,function(b){a.hide();this._handleError(d.editor.del.errorDeleting,b,!0)}))}))})})).show(d.editor.del.prompt)}},_executeSave:function(b,a,g,e){if(this.editor.gxeAdaptor.getAllowEditMetadata()){var f=
new h({title:d.editor.save.dialogTitle,showOkCancelBar:!1});f.show(d.editor.save.working).then(c.hitch(this,function(){this.editor.gxeAdaptor.saveXml(b,a,e).then(c.hitch(this,function(){this.lastSavedXml=a;setTimeout(c.hitch(this,function(){f.hide();g&&this._close()}),1500)}),c.hitch(this,function(a){f.hide();this._handleError(d.editor.save.errorSaving,a,!0)}))}))}},_download:function(b,a,c){null===a&&(a="metadata");var e;e=a+".xml";window.navigator&&window.navigator.msSaveOrOpenBlob?window.navigator.msSaveOrOpenBlob(new Blob([b],
{type:"text/xml"}),e):(e=d.editor.download.dialogTitle,c&&(e=d.editor.saveDraft.dialogTitle),c=new w({dialogTitle:e}),c.show(b,a))},_getTransformationTypes:function(b){var a=[];b=this.editor.getEditDocument();if(!b||!b.documentType.isIso)return a;t.forEach(this.editor.gxeContext.filterDocumentTypes(),function(c){c.key!==b.documentType.key&&c.isIso&&b.documentType.isIso&&a.push(c)});return a},_handleError:function(b,a,c){if(a)try{console.error(a)}catch(e){}c&&(new h({title:d.editor.errorDialog.dialogTitle,
showOk:!1,cancelLabel:d.general.close})).show(b,"gxeIconError",a)},_initializeView:function(){var b=this.editor.gxeAdaptor.getAllowEditMetadata(),a=this.editor.gxeContext.allowView,g=this.editor.gxeContext.allowViewXml,e=c.hitch(this,function(e,f){r.set(this.commonToolset,"display","");if(f&&b){this._setMode("edit");var m=this.editor.gxeContext.filterDocumentTypes()[0];this._fadeOut(d.editor.primaryToolbar.loadingDocument,c.hitch(this,function(){this.editor.loadEditor(m,null,!0,!1).then(c.hitch(this,
function(){this._fadeIn()}),c.hitch(this,function(a){this._fadeIn();this._handleError(d.editor.primaryToolbar.errors.errorLoadingDocument,a,!0)}))}))}else!a&&(!g&&b)&&(e="edit"),this._setMode(e),this._fadeIn()}),f=this.editor.viewDocumentPane,m,q=null,s,h=this._parseXml(this.editor.gxeAdaptor.getOriginalXml());h.documentType?(m=h.documentType,q=h.xmlString,s=h.xmlDocument,b&&!a?(r.set(this.commonToolset,"display",""),this._setMode("edit"),this._loadEditor()):this._fadeOut(d.editor.primaryToolbar.initializing,
c.hitch(this,function(){this.editor.loadView(m,s,!0).then(c.hitch(this,function(a){f.xmlString=q;this.editor.xmlPane.setXml(q,a.originalTitle);e("view")}),c.hitch(this,function(a){e("view");this._handleError(d.editor.primaryToolbar.errors.errorGeneratingView,a,!0)}))}))):h.xmlDocument?(!a&&b?this.editor.editDocumentPane.showMessage(d.editor.xmlViewOnly):f.showMessage(d.editor.xmlViewOnly),e("viewXml")):(f.showMessage(d.editor.noMetadata),e("view",!0))},_loadEditor:function(){if(this.editor.gxeAdaptor.getAllowEditMetadata()){var b,
a=this._parseXml(this.editor.gxeAdaptor.getOriginalXml());a.documentType?this._fadeOut(d.editor.primaryToolbar.startingEditor,c.hitch(this,function(){this.editor.loadEditor(a.documentType,a.xmlDocument,!1,!0).then(c.hitch(this,function(){this._fadeIn()}),c.hitch(this,function(a){this._fadeIn();this._handleError(d.editor.primaryToolbar.errors.errorLoadingDocument,a,!0)}))})):(b=d.editor.load.noMetadata,a.xmlDocument&&(b=d.editor.load.unrecognizedMetadata),this._showLoadDialog(b))}},_loadView:function(){var b=
this.editor.getEditDocument();if(b){var a=this.editor.viewDocumentPane,g=new l({ignoreErrors:!0}),e=b.generateXml(g);this._compareXmls(e,a.xmlString)?this._setMode("view"):(n.add(this.viewButton.domNode,"current"),n.remove(this.viewXmlButton.domNode,"current"),n.remove(this.editButton.domNode,"current"),this._fadeOut(d.editor.primaryToolbar.generatingView,c.hitch(this,function(){this._setMode("view");var f=b.documentType,g=p.parseFromString(e);this.editor.loadView(f,g,!1).then(c.hitch(this,function(b){a.xmlString=
e;a.hideMessage();this.editor.xmlPane.setXml(e,b.originalTitle);this._fadeIn()}),c.hitch(this,function(b){a.hideMessage();this._fadeIn();this._handleError(d.editor.primaryToolbar.errors.errorGeneratingView,b,!0)}))})))}else this._setMode("view")},_parseXml:function(b){var a={documentType:null,xmlString:b,xmlDocument:null};if(!b)return a;var c=null;try{c=p.parseFromString(b)}catch(d){return a}a.xmlDocument=c;b=this.editor.gxeContext.filterDocumentTypes();var f=new v;a.documentType=f.interrogate(c,
b);return a},_save:function(b){if(this.editor.gxeAdaptor.getAllowEditMetadata()){var a=this.editor.getEditDocument();if(a){this.editor.validationPane.clearMessages();var d=new l({isSaveAsDraft:!0,validationPane:this.editor.validationPane}),e=a.generateXml(d),f=d.documentTitle;if(!d.hadValidationErrors&&!(null===f||0===f.length))b.isSaveAsDraft?this._download(e,f,!0):b.showDialog?(b=new y({editor:this.editor,gxeDocument:a,onSave:c.hitch(this,function(b,c,d){b.hide();this._executeSave(a,e,c,d)})}),
b.show()):this._executeSave(a,e,b.isSaveAndClose,b.bPushToItem)}}},_showLoadDialog:function(b){(new x({editor:this.editor,prompt:b,onSelect:c.hitch(this,function(a,b,e,f){a.hide();this._fadeOut(d.editor.primaryToolbar.loadingDocument,c.hitch(this,function(){this.editor.loadEditor(b,e,f,!1).then(c.hitch(this,function(){this._fadeIn()}),c.hitch(this,function(a){this._fadeIn();this._handleError(d.editor.primaryToolbar.errors.errorLoadingDocument,a,!0)}))}))}),onSelectPullItem:c.hitch(this,function(a){a.hide();
this.editor.gxeAdaptor.pullItem(this.editor.getEditDocument())})})).show()},_showTransformDialog:function(b,a){(new z({editor:this.editor,documentTypes:a,prompt:null,onSelect:c.hitch(this,function(a,e){a.hide();this._fadeOut(d.editor.transform.working,c.hitch(this,function(){var a=new A({gxeDocument:b,toDocumentType:e}),g=new l({ignoreErrors:!0}),a=b.generateXml(g,a),g=null;if(a)try{g=p.parseFromString(a)}catch(h){g=null,console.error(h)}this.editor.loadEditor(e,g,!1,!1).then(c.hitch(this,function(a){a.documentType.afterTransform(a,
b);this._fadeIn()}),c.hitch(this,function(a){this._fadeIn();this._handleError(d.editor.transform.errorTransforming,a,!0)}))}))})})).show()},_validate:function(b){var a=this.editor.getEditDocument();a&&(this.editor.validationPane.clearMessages(),b=new l({isSaveAsDraft:b,validationPane:this.editor.validationPane}),a.generateXml(b),b.hadValidationErrors||(new h({title:d.editor.validate.dialogTitle,showCancel:!1})).show(d.editor.validate.docIsValid,null,null))}});u("extend-esri")&&c.setObject("dijit.metadata.editor.PrimaryToolbarMixin",
k,B);return k});