//>>built
(function(d,u){"function"===typeof define&&define.amd?define("esri/workers/heatmapCalculator",[],u):d.HeatmapCalculator=u();if(d.importScripts&&"function"===typeof d.importScripts){var t;d.addEventListener("message",function(m){var a=m.data,e=a.action;m=a.msgId;e&&m&&("initialize"==e?(t=new d.HeatmapCalculator(a),postMessage({msgId:m})):"calculate"==e&&(a=t.calculateImageData(a),postMessage({msgId:m,imageData:a},a)))},!1)}})(this,function(){function d(a){a=a||{};this.radius=a.blurRadius||10;this.maxVal=
a.maxPixelIntensity;this.minVal=a.minPixelIntensity;this.field=a.field;this.fieldOffset=a.fieldOffset;this.width=a.width;this.height=a.height;this.gradient=a.gradient;this.stats=null}function u(a,e){for(var g=Array(a),b=0;b<a;b++)for(var c=g[b]=Array(e),f=0;f<e;f++)c[f]=0;return g}function t(a,e){return a-e}var m=window.ArrayBuffer?!0:!1;d.prototype.calculateImageData=function(a){var e=this.radius=a.blurRadius||this.blurRadius;this.maxVal=null!=a.maxPixelIntensity?a.maxPixelIntensity:this.maxPixelIntensity;
this.minVal=null!=a.minPixelIntensity?a.minPixelIntensity:this.minPixelIntensity;var g=this.field="field"in a?a.field:this.field,b=this.fieldOffset="fieldOffset"in a?a.fieldOffset:this.fieldOffset,c=a.screenPoints,f=a.gradient;if(f)this.gradient=f;else if(this.gradient)f=this.gradient;else return!1;var k=a.features,h=a.mapinfo;c||(k&&h?c=this.screenPoints=this._calculateScreenPoints(k,h):!h&&this.screenPoints&&(k=!0,a.width&&a.width!=this.width&&(k=!1,this.width=a.width),a.height&&a.height!=this.height&&
(k=!1,this.height=a.height),k?c=this.screenPoints:this.screenPoints=null));if(!c)return!1;k=h.width||a.width||this.width;a=h.height||a.height||this.height;e=this._calculateIntensityMatrix(c,k,a,e,g,b);this._lastMatrix=e.matrix;this._maxIntVal=e.max;return this._createImageData(k,a,this._lastMatrix,f)};d.prototype._calculateScreenPoints=function(a,e){var g=e.resolution,b=e.width,c=e.height,f=e.extent,k=[];if(f)g||(g=c?Math.abs(f[3]-f[1])/c:Math.abs(f[2]-f[0])/b);else return!1;b=0;for(c=a.length;b<
c;b++){var h=a[b];k[b]={x:Math.round((h.geometry.x-f[0])/g),y:Math.round((f[3]-h.geometry.y)/g),attributes:h.attributes}}return k};d.prototype._calculateIntensityMatrix=function(a,e,g,b,c,f){var k=u(g,e),h=Math.round(4.5*b),r=b*b,d=[],l=2*h+1,p=-1,n=1,q=-Infinity,s;f=f||0;for(c=function(a){return"function"==typeof a?a:a?"abs"==f?function(b){return-1*+b.attributes[a]}:function(b){return+b.attributes[a]+f}:function(){return 1}}(c);++p<l;)d[p]=Math.exp(-Math.pow(p-h,2)/(2*r))/Math.sqrt(2*Math.PI)*(b/
2);for(p=0;p<a.length;p++){s=a[p];b=s.x-h;var r=s.y-h,l=b,m=r,n=+c(s);if(!(isNaN(n)||null===n))for(var t=Math.min(s.y+h,g-1),w=Math.min(s.x+h,e-1);r<=t;){for(var x=d[r-m];b<=w;)-1<b&&-1<r&&(s=k[r][b]+=x*d[b-l]*n,s>q&&(q=s)),b++;r++;b=l}}return{matrix:k,max:q}};d.prototype._createImageData=function(a,e,g,b){if(!m)return this._createPixelData(a,e,g,b);var c=new Uint32Array(a*e);b=b.buffer?new Uint32Array(b.buffer):new Uint32Array((new Uint8Array(b)).buffer);for(var f=this.minVal,k=b.length/(this.maxVal-
f),h=0;h<e;h++)for(var r=g[h],d=0;d<a;d++){var l=Math.floor((r[d]-f)*k);c[h*a+d]=0>l?b[0]:l<b.length?b[l]:b[b.length-1]}return c};d.prototype._createPixelData=function(a,e,g,b){for(var c=Array(4*a*e),f=this.minVal,k=b.length/4/(this.maxVal-f),h=3,d=0;d<e;d++)for(var m=g[d],l=0;l<a;l++){var p=4*(d*a+l)+3,n=4*Math.floor((m[l]-f)*k)+3;3>n?n=3:n>b.length-1&&(n=b.length-1);for(h=4;h--;)c[p-h]=b[n-h]}return c};d.calculateStats=function(a,e){if(!a)return!1;for(var g=a.length,b=0,c=0,f=0,k=0,h=Infinity,d=
-Infinity,m,l,p,n,q;g--;){p=a[g];for(m=p.length;m--;)if(q=p[m],!e||e(q))n||(n=q),l=q-n,k+=q,b+=l,c+=l*l,q<h&&(h=q),q>d&&(d=q),f++}return 0<f?{mean:k/f,stdDev:Math.sqrt((c-b*b/f)/f),min:h,max:d,mid:(d-h)/2}:{mean:0,stdDev:0,min:0,max:0,mid:0}};d.getBinnedValues=function(a){function e(a,b,c){for(var d=[];a<b;a+=c)d.push(a);return d}a=a||{};var g=a.stats,b=a.min,c=a.max,f=a.bins,d=a.count,h=a.size;a=a.values;if(!a)return!1;g&&(null!=g.max&&null!=g.min)&&(b=g.min,c=g.max);if(!f)if(h){null==b&&(b=0);if(null==
c){if(null==d)return!1;c=b+d*h}f=e(b,c,h)}else if(d){g&&null!=g.min&&null!=g.max?(b=g.min,c=g.max):null!=c&&(0<c&&null==b)&&(b=0);if(null==b||null==c)return!1;f=e(b,c,(c-b)/d)}for(var d=f.length,g=u(d,0),b=a.length,m,v,l;b--;){h=a[b];for(c=h.length;c--;){m=h[c];for(l=1;l<d&&!(v=f[l],m<v);l++);g[l-1].push(m)}}return g.map(function(a){return a.sort(t)})};d.getHistogramData=function(a){a=a||{};var e=a.binnedData,g=a.stats,b=a.byStdDev,c=a.matrix;a=a.binOptions||{};if(!e)if(c){if(a.values=c,b&&(g||(g=
d.calculateStats(c)),a.size=g.stdDev),a.stats=g,e=d.getBinnedValues(a),!e)return!1}else return!1;var f;if(a.bins)a=a.bins;else{a=[];for(b=0;b<e.length;b++)c=e[b],a.push(c[0])}f=[];for(b=0;b<a.length-1;b++)c=a[b],f[b]={range:[c,a[b+1]],count:c.length};g?e=g.max:(c=e[b],e=c[c.length-1]);c=a[b];f[b]={range:[c,e],count:c.length};return f};return d});