//>>built
define("esri/dijit/analysis/HelpWindow","require dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/_base/event dojo/_base/kernel dojo/aspect dojo/has dojo/dom-construct dojo/dom-class dojo/dom-attr dojo/dom-style dojo/query dojo/window dojo/dom-geometry dijit/_Widget dijit/TooltipDialog dijit/popup ../../kernel ../../lang ../../request ../_EventedWidget dojo/i18n!../../nls/jsapi".split(" "),function(g,n,e,f,B,C,h,s,p,D,E,F,t,u,v,w,x,y,l,z,q,A,G,r){e=e([x],{declaredClass:"esri.dijit.analysis.HelpWindow",
i18n:null,onlineHelpMap:null,showLearnMore:!1,"class":"esriAnalyisHelpWindow",postMixInProperties:function(){this.inherited(arguments);this.i18n={};f.mixin(this.i18n,r.common);f.mixin(this.i18n,r.analysisHelp)},postCreate:function(){this.inherited(arguments);var b=["ar","he"],a,d;this.onlineHelpMap={};for(a=0;a<b.length;a+=1)d=b[a],h.locale&&-1!==h.locale.indexOf(d)&&(-1!==h.locale.indexOf("-")?-1!==h.locale.indexOf(d+"-")&&(this._isRightToLeft=!0):this._isRightToLeft=!0);b=g.toUrl("./help/helpmap.json");
A({url:b}).then(f.hitch(this,function(a){this.onlineHelpMap=a.map}))},_getAbsoluteUrl:function(b){if(/^https?\:/i.test(b))return b;if(/^\/\//i.test(b))return window.location.protocol+b;if(/^\//i.test(b))return window.location.protocol+"//"+window.location.host+b},_computeSize:function(b){var a={w:400,h:200};p("esri-mobile")?a={w:"90%",h:"90%"}:-1!==b.indexOf("Category")?(a.w=400,a.h=320):-1!==b.indexOf("Tool")?(a.w=400,a.h=320):-1!==b.indexOf("toolDescription")&&(a.w=400,a.h=520);return a},_setHelpTopicAttr:function(b){this.tooltipHelpDlg&&
(l.close(this.tooltipHelpDlg),this.tooltipHelpDlg.destroy(),this.tooltipHelpDlg=null);var a,d,c,m;this.showLearnMore=!1;d=this._analysisGpServer&&-1!==this._analysisGpServer.indexOf("dev")?"dev":this._analysisGpServer&&-1!==this._analysisGpServer.indexOf("qa")?"uat":"";a=f.clone(h.locale);"nb"===a&&(a="no");c=g.toUrl("esri/dijit/analysis/help/"+this.helpFileName+".html");q.isDefined(this.onlineHelpMap[this.helpFileName])&&q.isDefined(this.onlineHelpMap[this.helpFileName][b])&&(this.showLearnMore=
!0,m="http://doc"+d+".arcgis.com/en/arcgis-online/use-maps/"+this.onlineHelpMap[this.helpFileName][b]);-1!==n.indexOf("ar cs da de es el et fi fr it ja ko lt lv ru nl no pl pt-br pt-pt ro sv th tr vi zh-cn zh-hk zh-tw".split(" "),a)&&(-1!==a.indexOf("-")&&(c=a.split("-"),a=c[0]+"-"+c[1].toUpperCase()),c=g.toUrl("esri/dijit/analysis/help/"+a+"/"+this.helpFileName+".html"));-1!==n.indexOf("ar de es fr it ja ko ru nl pl pt-br pt-pt ro zh-cn zh-hk zh-tw".split(" "),a)&&this.showLearnMore&&(m="http://doc"+
d+".arcgis.com/"+a+"/arcgis-online/use-maps/"+this.onlineHelpMap[this.helpFileName][b]);this._size=d=this._computeSize(b);this.tooltipHelpDlg=new y({preload:!0,content:"\x3cdiv class\x3d'' style\x3d'position:relative'\x3cdiv class\x3d'sizer content'\x3e\x3cdiv class\x3d'contentPane'\x3e\x3cdiv class\x3d'esriFloatTrailing' style\x3d'padding:0;'\x3e\x3ca href\x3d'#' class\x3d'esriAnalysisCloseIcon' title\x3d'"+this.i18n.close+"'\x3e\x3c/a\x3e\x3c/div\x3e\x3ciframe frameborder\x3d'0'  id\x3d'"+b+"' src\x3d'"+
c+"#"+b+"' width\x3d'"+d.w+"' height\x3d'"+d.h+"' marginheight\x3d'0' marginwidth\x3d'0'\x3e\x3c/iframe\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'sizer'\x3e\x3cdiv class\x3d'actionsPane'\x3e\x3cdiv class\x3d'actionList"+(this.showLearnMore?"'\x3e":" hidden'\x3e")+"\x3ca class\x3d'action zoomTo' href\x3d'"+(this.showLearnMore?m:"#")+"' target\x3d'_help'\x3e"+this.i18n.learnMore+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e","class":"esriHelpPopup esriHelpPopupWrapper esriAnalyisHelpWindow"});
this.tooltipHelpDlg.startup()},show:function(b,a){this.helpFileName=a.helpFileName;this._analysisGpServer=a.analysisGpServer;this.set("helpTopic",a.helpId);var d=s.after(l,"open",f.hitch(this,function(){u(".esriAnalysisCloseIcon",this.tooltipHelpDlg.domNode).on("click",f.hitch(this,this.close));d.remove()})),c=b.pageX,h=v.getBox(),e,k,g;g=!1;a.helpParentNode&&(e=a.helpParentNode);e&&(k=w.position(e));k&&h.w-b.pageX<k.w?(g=!0,c=k.x-this._size.w-10,this._isRightToLeft&&(c-=10)):this._isRightToLeft&&
c-40<this._size.w&&(c=k.w+this._size.w+80);l.open({popup:this.tooltipHelpDlg,x:!0===this._isRightToLeft||g?c-40:c+40,y:b.screenY-b.pageY+10,onCancel:f.hitch(this,function(){this.close()}),onExecute:function(){this.close()}});this.tooltipHelpDlg.domNode.parentNode&&t.set(this.tooltipHelpDlg.domNode.parentNode,"overflowY","hidden")},close:function(b,a){l.close(this.tooltipHelpDlg)}});p("extend-esri")&&f.setObject("dijit.analysis.HelpWindow",e,z);return e});