//>>built
require({cache:{"url:esri/dijit/templates/_ObliqueRotationWidget.html":'\x3cdiv\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"gaugeNode" class\x3d"esriObliqueRotationWidgetGauge"\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/_ObliqueRotationWidget","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../kernel ../lang ./_EventedWidget dijit/_Widget dijit/_TemplatedMixin dojo/text!./templates/_ObliqueRotationWidget.html dojo/_base/html dojo/on dojox/dgauges/CircularGauge ./ObliqueViewer/OVCircularScale dojox/dgauges/CircularRangeIndicator ./ObliqueViewer/OVCircularValueIndicator dojox/dgauges/LinearScaler dojo/dom-geometry dojo/dom-construct dojo/i18n!../nls/jsapi dojo/dom-style dojo/query dojo/dom-attr".split(" "),function(e,
f,g,n,p,d,q,r,s,t,A,u,v,w,h,k,x,y,l,z,m,B,C,D){e=e([q,r,s],{baseClass:"esriObliqueRotationWidget",declaredClass:"esri.dijit._ObliqueRotationWidget",templateString:t,azimuthAngle:0,azimuthField:"SensorAzimuth",isNadir:!1,_rangeIndicatorWidth:8,constructor:function(a,b){f.mixin(this,a);this._i18n=z;this.isNadir=!d.isDefined(this.azimuthAngle)},postCreate:function(){this.inherited(arguments);this._coords=this.domNode.getBoundingClientRect();this._computeCircleRadius();this._getCenter();this.refresh()},
startup:function(){this.inherited(arguments);this._setupGauge();this._addTooltips()},_setupGauge:function(){var a=this;this._gauge=new v({value:0,font:{family:"Helvetica",style:"normal",size:"10pt",color:"black",weight:"bold"},style:"margin: -2px;"},this.gaugeNode);this._addGaugeBackground();this._addGaugeScale();this._addGaugeIndicators();this._gauge.startup();this.own(u(this._gauge.domNode,"mouseup",function(b){a._getCenter();var c=b.pageX-a._centerLocnInPage[0];b=b.pageY-a._centerLocnInPage[1];
10>=Math.abs(c)&&10>=Math.abs(b)?(a._scale.azimuthAngle=null,a._switchToNadir()):(a.azimuthAngle=a._convertAngleToAzimuthNotation(a._calculateAngleFromXY(c,b)),a._switchToOblique())}));this.own(this._gauge.on("endEditing",f.hitch(this,function(b){a.isNadir||(this.snap&&this._snap(),a.azimuthAngle=this._convertAngleToAzimuthNotation(b.indicator.value),a.emit("azimuth-change",{azimuth:a.azimuthAngle}))})));this.on("azimuth-change",function(){a.gaugeNode&&(a.isNadir?(a.rotateAngle=0,a._scale.azimuthAngle=
null,m.set(a.gaugeNode,"transform","none")):(a.rotateAngle=a.rotateAngle||0,a.rotateAngle=Math.abs(a.rotateAngle+a.azimuthAngle)>Math.abs(a.rotateAngle-(360-a.azimuthAngle))?360-a.azimuthAngle:0-a.azimuthAngle,m.set(a.gaugeNode,"transform","rotate("+a.rotateAngle+"deg)"),a._scale.azimuthAngle=a.azimuthAngle));a._azimuthIndicator.azimuthAngle=a.azimuthAngle;a.textNodes=a.gaugeNode.querySelectorAll("text")})},_addGaugeBackground:function(){var a="M "+this._center.join(",")+"m "+(0-this._radius)+",0 a "+
this._radius+","+this._radius+" 0 1,0 "+2*this._radius+",0 a "+this._radius+","+this._radius+" 0 1,0 "+(0-2*this._radius)+",0";this._gauge.addElement("background",function(b){b.createPath({path:a}).setFill("rgba(255,255,255,0.5)").setStroke("rgba(89, 106, 114, 1)")});this._addNadirDataIndicator()},_addNadirDataIndicator:function(){var a="M "+this._center.join(",")+"m -7,0 a 7,7 0 1,0 14,0 a 7,7 0 1,0 -14,0";this._gauge.addElement("nadirDataIndicator",function(b){b.createPath({path:a}).setFill("rgba(54, 104, 178, 0.5)").setStroke("rgba(0,0,0, 1)")})},
_addGaugeScale:function(){this._scale=new w({originX:this._center[0],originY:this._center[1],radius:this._radius,startAngle:0,endAngle:359.999,orientation:"clockwise",scaler:new x({minimum:0,maximum:360,majorTickInterval:90,minorTickInterval:45}),tickShapeFunc:function(a,b,c){if(!c.isMinor)return a.createLine({x1:0,y1:0,x2:c.isMinor?15:20,y2:0}).setStroke({color:"black",width:1})},labelGap:5,tickLabelFunc:function(a){var b=["E","S","W","N"];return!a.isMinor?0===a.value%90?b[a.value/90]:a.value:" "}});
this._gauge.addElement("scale",this._scale)},_addGaugeIndicators:function(){var a=new h({value:359.9999,radius:this._radius-8,startThickness:6,endThickness:6,fill:"rgba(0,0,0,0.9)"});this._scale.addIndicator("indicatorBg",a);this._azimuthIndicator=this._createObliqueIndicator();this._nadirIndicator=this._createNadirIndicator();this.isNadir?this._scale.addIndicator("nadir_indicator",this._nadirIndicator):this._scale.addIndicator("azimuth_indicator",this._azimuthIndicator)},_convertAngleToAzimuthNotation:function(a){if(d.isDefined(a))return(a+
90)%360},_convertAngleToGaugeNotation:function(a){if(d.isDefined(a))return(a+270)%360},_computeCircleRadius:function(){var a;a=Math.min(this._coords.width/2,this._coords.height/2);return this._radius=a=Math.floor(a-2)},showAvailableData:function(a){var b=this;if(a=a||this.features){g.forEach(this._availableDataIndicators,function(a){b._scale.removeIndicator(a)});this._availableDataIndicators=[];this.features=a;for(var c=0,d,c=0;c<a.length;c++)d=new h({start:this._convertAngleToGaugeNotation(a[c].attributes[this.azimuthField]-
5),value:this._convertAngleToGaugeNotation(a[c].attributes[this.azimuthField]+5),radius:this._radius-1,startThickness:7,endThickness:7,fill:"#3668B2",stroke:"#3668B2"}),this._scale.addIndicator("indicator_"+c,d),this._availableDataIndicators.push("indicator_"+c)}},refresh:function(a){f.mixin(this,a);this.showAvailableData()},_getCenter:function(){var a=[],b,c=[];this._coords=this.gaugeNode.getBoundingClientRect();a.push(Math.ceil(this._coords.width/2));a.push(Math.ceil(this._coords.height/2));b=y.position(this.gaugeNode);
c.push(b.x+a[0]);c.push(b.y+a[1]);this._centerLocnInPage=c;return this._center=a},_snap:function(){if(this._azimuthIndicator&&this.features&&this.features.length){var a=this._convertAngleToAzimuthNotation(this._azimuthIndicator.value),b,c,d=1E3;g.forEach(this.features,function(e){c=Math.min(Math.abs(e.attributes[this.azimuthField]-a),Math.abs(e.attributes[this.azimuthField]-a-360));c<=d&&(b=e.attributes[this.azimuthField],d=c)},this);this.azimuthAngle=b;this._azimuthIndicator.set("value",this._convertAngleToGaugeNotation(this.azimuthAngle))}},
_switchToNadir:function(){this.isNadir||(this._scale.azimuthAngle=null,this._nadirIndicator=this._createNadirIndicator(),this._scale.removeIndicator("azimuth_indicator"),this._scale.addIndicator("nadir_indicator",this._nadirIndicator),this.isNadir=!0,this.emit("azimuth-change",{azimuth:null}))},_switchToOblique:function(){this.isNadir&&(this._azimuthIndicator=this._createObliqueIndicator(),this._scale.removeIndicator("nadir_indicator"),this._scale.addIndicator("azimuth_indicator",this._azimuthIndicator),
this._snap(),this.isNadir=!1,this.emit("azimuth-change",{azimuth:this.azimuthAngle}))},_createNadirIndicator:function(){return new k({title:"Nadir",interactionMode:"none",indicatorShapeFunc:function(a){return a.createPolyline([-7,0,7,0,0,0,0,7,0,-7]).setStroke({color:"#000000",width:1})},value:0})},_createObliqueIndicator:function(){var a=this;return new k({interactionArea:"gauge",title:"Change Azimuth",indicatorShapeFunc:function(b){return b.createPolyline([0,-1,a._radius-1,-10,a._radius-1,10,0,
1,0,-1]).setFill("rgba(50, 100, 200, 0.5)").setStroke("rgba(50, 100, 200, 0.5)")},value:this._convertAngleToGaugeNotation(this.azimuthAngle),azimuthAngle:this._convertAngleToGaugeNotation(this.azimuthAngle)})},_calculateAngleFromXY:function(a,b){var c;c=Math.atan2(b,a);return 180*(c/Math.PI)+(0<c?0:360)},_addTooltips:function(){var a=this,b;g.forEach([{top:0,left:this._radius-5,direction:"north",angle:0},{top:this._radius-5,left:2*(this._radius-5),direction:"east",angle:90},{top:2*(this._radius-5),
left:this._radius,direction:"south",angle:180},{top:this._radius-5,left:0,direction:"west",angle:270},{top:this._radius-5,left:this._radius-5,direction:"nadir",angle:null}],function(c){b=l.create("div");b.style.position="absolute";b.style.top=c.top+"px";b.style.left=c.left+"px";b.style.height="10px";b.style.width="10px";b.style.cursor="pointer";b.style.zIndex=999;b.id=this.domNode.id+"_tooltip_"+c.direction;l.place(b,this.gaugeNode);b.title=this._i18n.widgets.obliqueViewer[c.direction+"Tooltip"];
b.onclick=function(){d.isDefined(c.angle)&&(a.azimuthAngle=c.angle,a._azimuthIndicator.set("value",a._convertAngleToGaugeNotation(c.angle)),a.snap&&a._snap(),a.emit("azimuth-change",{azimuth:a.azimuthAngle}))}},this)},setAzimuth:function(a){d.isDefined(a)&&(this.azimuthAngle=a,this.isNadir?this._switchToOblique():this._azimuthIndicator.set("value",this._convertAngleToGaugeNotation(this.azimuthAngle)))}});n("extend-esri")&&f.setObject("dijit._ObliqueRotationWidget",e,p);return e});