//>>built
define("esri/dijit/ObliqueViewer","dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../tasks/QueryTask ../tasks/query ./_EventedWidget dijit/_Widget ./_ObliqueRotationWidget dojo/_base/array ../ImageSpatialReference ../tasks/ImageServiceProjectTask ../tasks/ProjectParameters ../layers/MosaicRule ../geometry/Extent ../geometry/Polygon ../lang ../config ./RasterList dojo/store/Observable dojo/store/Memory dojo/Deferred".split(" "),function(h,m,v,w,x,q,y,z,A,k,B,C,D,f,g,n,p,e,E,r,s,t){h=h([y,z],
{declaredClass:"esri.dijit.ObliqueViewer",azimuthField:"SensorAzimuth",elevationThreshold:70,elevationField:"SensorElevation",snap:!0,_refreshOK:!0,isNadir:!1,showThumbnail:!0,noQueryOnExtentChange:!1,azimuthTolerance:10,rasterListRefresh:!0,extents:[],maxExtentIdx:5,currentExtentIdx:null,setNextExtent:function(){if(!(this.currentExtentIdx>=this.maxExtentIdx||this.currentExtentIdx>=this.extents.length-1)){var a=this;this.currentExtentIdx++;mosaicRule=new f;mosaicRule.method=f.METHOD_LOCKRASTER;mosaicRule.lockRasterIds=
[this.extents[this.currentExtentIdx].spatialReference.icsid];a.imageServiceLayer.setMosaicRule(mosaicRule,!0);a._refreshOK=!1;a.map.spatialReference=this.extents[this.currentExtentIdx].spatialReference;zoomDuration=e.defaults.map.zoomDuration;e.defaults.map.zoomDuration=0;a.map.setExtent(this.extents[this.currentExtentIdx]).then(function(){a._refreshOK=!0;e.defaults.map.zoomDuration=zoomDuration})}},setPreviousExtent:function(){if(!(0>=this.currentExtentIdx)){var a=this;this.currentExtentIdx--;mosaicRule=
new f;mosaicRule.method=f.METHOD_LOCKRASTER;mosaicRule.lockRasterIds=[this.extents[this.currentExtentIdx].spatialReference.icsid];a.imageServiceLayer.setMosaicRule(mosaicRule,!0);a._refreshOK=!1;a.map.spatialReference=this.extents[this.currentExtentIdx].spatialReference;zoomDuration=e.defaults.map.zoomDuration;e.defaults.map.zoomDuration=0;a.map.setExtent(this.extents[this.currentExtentIdx]).then(function(){a._refreshOK=!0;e.defaults.map.zoomDuration=zoomDuration})}},isPreviousAvailable:function(){},
isNextAvailable:function(){},_isICS:function(a){return!(!a.ics&&!a.icsid)},_initializeTasks:function(){this.obliqueRecordsQueryTask=new x(this.imageServiceUrl);this.projectTask=new C},_verifyRasterInfoFields:function(){return this.rasterInfoFields&&this.rasterInfoFields.length},_setupRasterList:function(){var a=this,b=[{name:this.imageServiceLayer.objectIdField,alias:"Object ID",display:!0},{name:this.azimuthField,alias:"Azimuth",display:!0},{name:this.elevationField,alias:this.elevationField,display:!0}];
this.rasterInfoFields=this._verifyRasterInfoFields()?this.rasterInfoFields:b;this.rasterList=new E({data:new r(new s),showThumbnail:this.showThumbnail,imageServiceUrl:this.imageServiceLayer.url,fields:this.rasterInfoFields},this.rasterListDiv);this.rasterList.on("raster-select",function(c){a.selectedRasterId=c[a.imageServiceLayer.objectIdField];a.setImage(a.selectedRasterId,a.map.extent);k.forEach(a.filteredRecords,function(c){delete c.attributes.selected;c.attributes[a.imageServiceLayer.objectIdField]===
a.selectedRasterId&&(c.attributes.selected=!0)});a._rotationWidget&&a._rotationWidget.setAzimuth(c[a.azimuthField])});this.rasterList.startup()},_setupRotationWidget:function(){var a=this;this._rotationWidget=new A({snap:this.snap,azimuthAngle:this.azimuthAngle},this.rotationDiv);this._rotationWidget.startup();this.own(this._rotationWidget.on("azimuth-change",function(b){b=b.azimuth;a.currentExtentIdx=0;a.extents=[];a.emit("azimuth-change",{azimuth:b});b?(a.azimuthAngle=b,a._checkExtentOrientation(),
a._filterByAzimuth(),a._rotationWidget.refresh({features:a.records}),a._refreshListDijit(a.filteredRecords),a._refreshImage(a.map.extent),a._oldAzimuth=b,a.isNadir=!1):a._switchToNadir()}))},_checkExtentOrientation:function(){var a=Math.abs((this._oldAzimuth-this.azimuthAngle)/90%2);this._azimuthExtentChanged=0.25>a||1.75<a?!1:!0},_refreshListDijit:function(a){a=this._prepareListData(a);this.rasterList&&this.rasterListRefresh&&this.rasterList.setData(a);this.emit("records-refresh",{records:this.records,
filteredRecords:this.filteredRecords})},_prepareListData:function(a){var b=[],c,d=this.imageServiceLayer.objectIdField;k.forEach(a,function(a){c=a.attributes;c.thumbnailUrl=this.imageServiceUrl+"/"+c[d]+"/thumbnail";b.push(c)},this);return new r(new s({data:b,idProperty:this.imageServiceLayer.objectIdField}))},_switchToNadir:function(){var a=!!this.map.extent.spatialReference.icsid,b=this.defaultNadirMosaicRule||this.imageServiceLayer.mosaicRule||new f;this._oldAzimuth=this.azimuthAngle=null;this._azimuthExtentChanged=
!1;b.method=b.method||f.METHOD_NONE;b.where=this.elevationField+"\x3e"+this.elevationThreshold;this.defaultNadirMosaicRule=b;this.imageServiceLayer.setMosaicRule(b,a);if(a){var c=this,d;this.projectGeometry(this.map.extent,this.nadirSpatialReference).then(function(a){c._verifyExtent(a[0])&&(c._refreshOK=!1,c.map.spatialReference=a[0].spatialReference,d=e.defaults.map.zoomDuration,e.defaults.map.zoomDuration=0,c.map.setExtent((new g(a[0])).setSpatialReference(a[0].spatialReference)).then(function(){c._refreshOK=
!0;c.isNadir=!0;e.defaults.map.zoomDuration=d;c.selectedRasterId=null;c.selectedRaster=null;c.filteredRecords=null}))})}},projectGeometry:function(a,b){var c=new D;b=b||this.map.spatialReference;c.geometries=[a];c.outSR=b;return this.projectTask.execute(c)},_verifyExtent:function(a){return!isNaN(a.xmin)&&!isNaN(a.xmax)&&!isNaN(a.ymin)&&!isNaN(a.ymax)},_refreshRecords:function(a){function b(b){c._verifyExtent(b[0])?(c.nadirExtent=b[0],c.search(c._trimExtent(c.nadirExtent,d)).then(function(b){if(!b||
!b.features||!b.features.length)return 0;c.records=b.features;c._rotationWidget&&c._rotationWidget.refresh({features:c.records});c.isNadir?c._refreshListDijit(c.records):(c._filterByAzimuth(),c._refreshListDijit(c.filteredRecords),a&&(c.filteredRecords&&c.filteredRecords.length)&&c._refreshImage(c.nadirExtent))})):(console.error("Oblique viewer: Project Operation returned invalid extent"),c.search(c._trimExtent(c.map.extent,d)).then(function(b){if(!b||!b.features||!b.features.length)return 0;c.records=
b.features;c._rotationWidget&&c._rotationWidget.refresh({features:c.records});c.isNadir?c._refreshListDijit(c.records):(c._filterByAzimuth(),c._refreshListDijit(c.filteredRecords),a&&(c.filteredRecords&&c.filteredRecords.length)&&c._refreshImage((new n(c.filteredRecords[0].geometry)).getExtent()))}))}var c=this,d=0.15;this.nadirSpatialReference.equals(this.map.extent.spatialReference)?b([this.map.extent]):this.projectGeometry(this.map.extent,this.nadirSpatialReference).then(b)},postCreate:function(){this.inherited(arguments);
(!this.map||!this.imageServiceLayer)&&console.error("ObliqueViewer: Map or Image service layer not provided.");this.imageServiceUrl=this.imageServiceLayer.url;this.nadirSpatialReference=this.map.extent.spatialReference;this._initializeTasks();(this.isNadir=!p.isDefined(this.azimuthAngle))&&this._switchToNadir();this.rotationDiv&&this._setupRotationWidget();if(this.rasterListDiv)if(this.imageServiceLayer.loaded)this._setupRasterList();else this.imageServiceLayer.on("load",m.hitch(this,this._setupRasterList));
this.sorter||(this.sorter=this._sortSpatially);this.own(this.map.on("extent-change",m.hitch(this,function(a){this._refreshOK&&!this.noQueryOnExtentChange&&(this._isICS(this.map.extent.spatialReference)||(this._nadirExtent=this.map.extent,this._switchToNadir()),this._refreshRecords(!0),this._azimuthExtentChanged=!1)})));p.isDefined(this.azimuthAngle)&&!this.noQueryOnExtentChange&&this._refreshRecords()},_refreshImage:function(a){!this.filteredRecords||!this.filteredRecords.length||this.selectedRasterId===
this.filteredRecords[0].attributes[this.imageServiceLayer.objectIdField]?this._refreshSavedExtents():this._setSelectedRaster(a)},_refreshSavedExtents:function(){this._isICS(this.map.extent.spatialReference)&&(!this.extents||!this.extents.length?(this.currentExtentIdx=0,this.extents=[]):(this.extents.length>this.maxExtentIdx&&(this.extents.shift(),this.currentExtentIdx--),this.currentExtentIdx<this.extents.length-1?this.currentExtentIdx=this.extents.length-1:this.currentExtentIdx++),this.extents.push(this.map.extent))},
setImage:function(a,b){if(!a)return console.error("Object ID of raster to be displayed not provided");var c=this,d,u;this.imageSpatialReference=new B({icsid:a,url:this.imageServiceUrl});this.projectGeometry(this._adjustExtentAspectRatio(b),this.imageSpatialReference).then(function(b){if(!c._verifyExtent(b[0]))return 0;d=new f;d.method=f.METHOD_LOCKRASTER;d.lockRasterIds=[a];c.imageServiceLayer.setMosaicRule(d,!0);c._refreshOK=!1;c.map.spatialReference=b[0].spatialReference;u=e.defaults.map.zoomDuration;
e.defaults.map.zoomDuration=0;c.map.setExtent((new g(b[0])).setSpatialReference(b[0].spatialReference)).then(function(){c._refreshOK=!0;e.defaults.map.zoomDuration=u;c._refreshSavedExtents()})})},search:function(a){if(!a)return console.error("Oblique viewer: no geometry provided for search.");var b,c=new t,d=this;b=new q;b.geometry=a;b.outFields=this._getQueryFields()||[this.imageServiceLayer.objectIdField,this.azimuthField];b.returnGeometry=!0;b.where=this.elevationField+"\x3c"+this.elevationThreshold;
b.outSpatialReference=a.spatialReference;b.spatialRel="esriSpatialRelContains";this.obliqueRecordsQueryTask.execute(b).then(function(a){c.resolve({features:d.sorter(d._processRecords(a.features))})});return c.promise},_sortSpatially:function(a){if(a&&a.length&&this.map.loaded){var b=0,c=0,d=a[0],e,f,g,h,b=0,l;l=(this.nadirExtent||this.map.extent).getCenter();this.selectedRaster&&this._extentContained(this.selectedRaster,this.nadirExtent)&&(k.some(a,function(c,b){if(c.attributes[this.imageServiceLayer.objectIdField]===
this.selectedRasterId)return g=a[b],a[b]=d,a[0]=g,!0},this),b=1);for(;b<a.length;b++){e=Math.sqrt((a[b].center.x-l.x)*(a[b].center.x-l.x)+(a[b].center.y-l.y)*(a[b].center.y-l.y));h=b;for(c=b+1;c<a.length;c++)f=Math.sqrt((a[c].center.x-l.x)*(a[c].center.x-l.x)+(a[c].center.y-l.y)*(a[c].center.y-l.y)),e>f&&(d=a[c],e=f,h=c);b!==h&&(g=a[b],a[b]=d,a[h]=g)}}return a},_filterByAzimuth:function(){this.filteredRecords=[];k.forEach(this.records,function(a){Math.min(Math.abs(a.attributes[this.azimuthField]-
this.azimuthAngle),Math.abs(a.attributes[this.azimuthField]-this.azimuthAngle-360))<=this.azimuthTolerance&&this.filteredRecords.push(a)},this);this.filteredRecords&&this.filteredRecords.length&&(this.filteredRecords[0].attributes.selected=!0)},_processRecords:function(a){var b;k.forEach(a,function(a){b=(new n(a.geometry)).setSpatialReference(this.nadirSpatialReference).getCentroid();a.center=b},this);return a},_computeAzimuthFilter:function(){var a=(this.azimuthAngle+350)%360,b=(this.azimuthAngle+
10)%360;return a<b?this.azimuthField+" BETWEEN "+a+" AND "+b:"("+this.azimuthField+" BETWEEN 0 AND "+b+" OR "+this.azimuthField+" BETWEEN "+a+" AND 360)"},_getIds:function(a){var b=[],c=this;k.forEach(a,function(a){b.push(a.attributes[c.imageServiceLayer.objectIdField])});return b},_adjustExtentAspectRatio:function(a){if(!this._azimuthExtentChanged){var b=0.45*a.getHeight(),c=0.45*a.getWidth(),d=a.getCenter();return a=new g(d.x-c,d.y-b,d.x+c,d.y+b,a.spatialReference)}b=a.getWidth();d=a.getHeight();
c=d>b?0.8<b/d?0.5:0.36:0.7<d/b?0.5:0.65;b=Math.min(d,b)*c;d=a.getCenter();return a=new g(d.x-b,d.y-b,d.x+b,d.y+b,a.spatialReference)},_setRasterListRefreshAttr:function(a){this._set("rasterListRefresh",a);a&&this._refreshListDijit(this.isNadir?this.records:this.filteredRecords)},_extentContained:function(a,b){if(!a||!b)return!1;var c=(new n(a.geometry)).getExtent();reducedExtent=this._trimExtent(c,0.2);return reducedExtent.contains(b)},setData:function(a,b){if(!a)return console.error("Oblique viewer: records not provided.");
b=b||this.map.extent;this._set("records",a);this._filterByAzimuth();if(this.filteredRecords&&this.filteredRecords.length)if(this._refreshListDijit(this.filteredRecords),this.imageServiceLayer.loaded)this._setSelectedRaster(b);else this.imageServiceLayer.on("load",m.hitch(this,function(){this._setSelectedRaster(b)}));else this.selectedRasterId=this.selectedRaster=null,this.emit("raster-select",{selectedRasterId:null})},_setSelectedRaster:function(a){this.selectedRaster=this.filteredRecords[0];this.selectedRasterId=
this.selectedRaster.attributes[this.imageServiceLayer.objectIdField];this.setImage(this.selectedRaster.attributes[this.imageServiceLayer.objectIdField],a);this.emit("raster-select",{selectedRasterId:this.selectedRasterId})},setExtent:function(a){var b=new t,c=this;this.projectGeometry(a,this.map.spatialReference).then(function(a){c._verifyExtent(a[0])&&c.map.setExtent(a[0]).then(function(){b.resolve()})});return b.promise},zoomToSelectedImage:function(){if(!p.isDefined(this.selectedRasterId))return console.error("Oblique viewer: no selected raster.");
if(this.isNadir)return 0;var a=this,b;this._getImageGeometry(this.selectedRasterId,this.map.spatialReference).then(function(c){c.features&&c.features.length&&(b=(new n(c.features[0].geometry)).setSpatialReference(a.map.spatialReference),a.map.setExtent(b.getExtent()))})},_getImageGeometry:function(a,b){var c=new q;c.objectIds=[a];c.returnGeometry=!0;c.outSpatialReference=b;return this.obliqueRecordsQueryTask.execute(c)},_getQueryFields:function(){var a=[];k.forEach(this.rasterInfoFields,function(b){b.name&&
a.push(b.name)});0>k.indexOf(a,this.azimuthField)&&a.push(this.azimuthField);0>k.indexOf(a,this.imageServiceLayer.objectIdField)&&a.push(this.imageServiceLayer.objectIdField);return a},_trimExtent:function(a,b){var c,d,e;c=a.ymax-a.ymin;d=c*(1-b);c*=1-b;e=a.getCenter();return new g({xmin:e.x-c/2,ymin:e.y-d/2,xmax:e.x+c/2,ymax:e.y+d/2,spatialReference:a.spatialReference})}});v("extend-esri")&&m.setObject("dijit.ObliqueViewer",h,w);return h});