//>>built
define("esri/dijit/Bookmarks","dojo/_base/declare dojo/_base/connect dojo/_base/lang dojo/_base/array dojo/aspect dojo/has dojo/keys dojo/query dojo/dom dojo/dom-construct dojo/dom-class dojo/dom-geometry dojo/window dojo/on dojo/dnd/Source dojo/dnd/Avatar dojo/i18n!../nls/jsapi dijit/a11yclick ../kernel ../domUtils ../geometry/Extent ./BookmarkItem ../Evented".split(" "),function(q,c,e,g,E,x,y,m,z,l,h,u,A,s,B,t,p,r,C,v,n,w,D){q=q(D,{declaredClass:"esri.dijit.Bookmarks",bookmarks:[],bookmarkDomNode:null,
bookmarkTable:null,initBookmarks:null,editable:null,map:null,_oldGenerateText:null,_customGenerateText:!1,_dndSource:null,_inputBox:null,_label:null,_css:{esriBookmarks:"esriBookmarks",esriBookmarkList:"esriBookmarkList",esriBookmarkTable:"esriBookmarkTable",esriBookmarkEditImage:"esriBookmarkEditImage",esriBookmarkRemoveImage:"esriBookmarkRemoveImage",esriBookmarkLabel:"esriBookmarkLabel",esriBookmarkItem:"esriBookmarkItem",esriBookmarkHighlight:"esriBookmarkHighlight",esriAddBookmark:"esriAddBookmark",
esriBookmarkEditBox:"esriBookmarkEditBox"},_clickHandlers:[],_mouseOverHandlers:[],_mouseOutHandlers:[],_removeHandlers:[],_editHandlers:[],_dndHandlers:[],_eventMap:{click:!0,edit:!0,remove:!0},onClick:function(){},onEdit:function(){},onRemove:function(){},constructor:function(a,b){this.map=a.map;this.editable=a.editable;this.initBookmarks=a.bookmarks;this.bookmarkDomNode=l.create("div");h.add(this.bookmarkDomNode,this._css.esriBookmarkList);this.bookmarkTable=l.create("div");h.add(this.bookmarkTable,
this._css.esriBookmarkTable);this.bookmarkDomNode.appendChild(this.bookmarkTable);b=z.byId(b);b.appendChild(this.bookmarkDomNode);this.srcNodeRef=b;h.add(this.srcNodeRef,this._css.esriBookmarks);this._dndSource=new B(this.bookmarkTable,{creator:this._avatarCreator,singular:!0,checkAcceptance:function(a,b){a.getItem(b[0].id);return this==a?!0:!1}});this._dndSourceNodes=this._dndSource.getAllNodes();this._dndHandlers.push(s(this._dndSource,"DndStart",e.hitch(this,function(a){a==this._dndSource&&(this._oldGenerateText=
t.prototype._generateText,t.prototype._generateText=e.hitch(this,this._generateText),this._customGenerateText=!0,this._inputBox&&this._finishEdit())})));this._dndHandlers.push(s(this._dndSource,"DndDrop",e.hitch(this,function(a){a==this._dndSource&&(this._syncBookmarksAfterReorder(),this.emit("reorder",this.bookmarks))})));this._dndHandlers.push(s(this._dndSource,"DndCancel",e.hitch(this,function(){this._customGenerateText&&(t.prototype._generateText=this._oldGenerateText,this._customGenerateText=
!1)})));this._addInitialBookmarks()},destroy:function(){this.map=null;g.forEach(this._clickHandlers,function(a){c.disconnect(a)});g.forEach(this._mouseOverHandlers,function(a){c.disconnect(a)});g.forEach(this._mouseOutHandlers,function(a){c.disconnect(a)});g.forEach(this._removeHandlers,function(a){c.disconnect(a)});g.forEach(this._editHandlers,function(a){c.disconnect(a)});l.destroy(this.bookmarkDomNode)},addBookmark:function(a){var b,d,k,f;"esri.dijit.BookmarkItem"==a.declaredClass?b=a:(b=new n(a.extent),
b=new w({name:a.name,extent:b}));this.editable?(k=p.widgets.bookmarks,f=k.NLS_bookmark_edit,k=k.NLS_bookmark_remove,d=l.create("div",{innerHTML:'\x3cdiv tabindex\x3d"0" role\x3d"button" class\x3d\'esriBookmarkLabel\'\x3e'+a.name+'\x3c/div\x3e\x3cdiv tabindex\x3d"0" role\x3d"button" title\x3d\''+k+"' class\x3d'esriBookmarkRemoveImage'\x3e\x3cbr/\x3e\x3c/div\x3e\x3cdiv tabindex\x3d\"0\" role\x3d\"button\" title\x3d'"+f+"' class\x3d'esriBookmarkEditImage'\x3e\x3cbr/\x3e\x3c/div\x3e"}),f=m(".esriBookmarkEditImage",
d)[0],k=m(".esriBookmarkRemoveImage",d)[0],this._removeHandlers.push(c.connect(k,r,this,"_removeBookmark")),this._editHandlers.push(c.connect(f,r,this,"_editBookmarkLabel"))):d=l.create("div",{innerHTML:"\x3cdiv tabindex\x3d\"0\" class\x3d'esriBookmarkLabel'\x3e"+a.name+"\x3c/div\x3e"});h.add(d,this._css.esriBookmarkItem);"esri.geometry.Extent"!=a.extent.declaredClass&&new n(a.extent);f=m(".esriBookmarkLabel",d)[0];this._clickHandlers.push(c.connect(f,r,e.hitch(this,"_onClickHandler",a)));this._mouseOverHandlers.push(c.connect(d,
"onmouseover",e.hitch(this,function(){h.add(d,this._css.esriBookmarkHighlight)})));this._mouseOutHandlers.push(c.connect(d,"onmouseout",e.hitch(this,function(){h.remove(d,this._css.esriBookmarkHighlight)})));this.bookmarks.push(b);this._dndSource.insertNodes(!1,[d]);this._dndSourceNodes=this._dndSource.getAllNodes();A.scrollIntoView(d);this._syncBookmarksAfterReorder()},removeBookmark:function(a){var b;b=m(".esriBookmarkLabel",this.bookmarkDomNode);b=g.filter(b,function(b){return b.innerHTML==a});
g.forEach(b,function(a){a.parentNode.parentNode.parentNode.removeChild(a.parentNode.parentNode)});for(b=this.bookmarks.length-1;0<=b;b--)this.bookmarks[b].name==a&&this.bookmarks.splice(b,1);this.onRemove()},hide:function(){v.hide(this.bookmarkDomNode)},show:function(){v.show(this.bookmarkDomNode)},_addInitialBookmarks:function(){if(this.editable){var a=l.create("div",{tabIndex:0,role:"button",innerHTML:"\x3cdiv\x3e"+p.widgets.bookmarks.NLS_add_bookmark+"\x3c/div\x3e"});h.add(a,this._css.esriBookmarkItem);
h.add(a,this._css.esriAddBookmark);this._clickHandlers.push(c.connect(a,r,this,this._newBookmark));this._mouseOverHandlers.push(c.connect(a,"onmouseover",e.hitch(this,function(){h.add(a,this._css.esriBookmarkHighlight)})));this._mouseOutHandlers.push(c.connect(a,"onmouseout",e.hitch(this,function(){h.remove(a,this._css.esriBookmarkHighlight)})));this.srcNodeRef.appendChild(a)}this.bookmarks=[];g.forEach(this.initBookmarks,function(a){this.addBookmark(a)},this)},_newBookmark:function(){var a,b,d,k,
f,c;c=this.map;a=p.widgets.bookmarks.NLS_new_bookmark;var e=c.extent;c.spatialReference._isWrappable()?(b=n.prototype._normalizeX(e.xmin,c.spatialReference._getInfo()).x,d=n.prototype._normalizeX(e.xmax,c.spatialReference._getInfo()).x,b>d&&(k=(f=c.spatialReference.isWebMercator())?2.0037508342788905E7:180,f=f?-2.0037508342788905E7:-180,Math.abs(b-k)>Math.abs(d-f)?d=k:b=f),c=new n(b,e.ymin,d,e.ymax,c.spatialReference)):c=e;a=new w({name:a,extent:c});this.addBookmark(a);a=m(".esriBookmarkItem",this.bookmarkDomNode);
c=a[a.length-1];a={target:{parentNode:null}};a.target.parentNode=c;this._editBookmarkLabel(a)},_removeBookmark:function(a){this.bookmarks.splice(a.target.parentNode.parentNode.parentNode.rowIndex,1);a.target.parentNode.parentNode.parentNode.removeChild(a.target.parentNode.parentNode);this.onRemove()},_syncBookmarksAfterReorder:function(){var a=[],b=this._dndSource.getAllNodes();g.forEach(b,e.hitch(this,function(b){var c=this._dndSourceNodes.map(function(a,c){if(a==b)return c}).filter(isFinite)[0];
a.push(this.bookmarks[c])}));this.bookmarks=a;this._dndSourceNodes=b},_generateText:function(){return this._dndSource&&this._dndSource.getSelectedNodes()[0]&&this._dndSource.getSelectedNodes()[0].firstChild.firstChild.innerHTML?this._dndSource.getSelectedNodes()[0].firstChild.firstChild.innerHTML:""},_editBookmarkLabel:function(a){this._inputBox&&this._finishEdit();var b;a=a.target.parentNode;b=u.position(a,!0);b=l.create("div",{innerHTML:"\x3cinput type\x3d'text' class\x3d'esriBookmarkEditBox' style\x3d'z-index: 999; left:"+
b.x+"px; top:"+b.y+"px;'/\x3e"});this._inputBox=m("input",b)[0];this._label=m(".esriBookmarkLabel",a)[0];this._inputBox.value=this._label.innerHTML==p.widgets.bookmarks.NLS_new_bookmark?"":this._label.innerHTML;c.connect(this._inputBox,"onkeyup",this,function(a){switch(a.keyCode){case y.ENTER:this._finishEdit()}});c.connect(this._inputBox,"onblur",this,"_finishEdit");this.srcNodeRef.appendChild(b);this._inputBox.focus();this._inputBox.select();b=u.position(a,!0);this._inputBox.style.left=b.x+"px";
this._inputBox.style.top=b.y+"px"},_finishEdit:function(){var a,b;try{this._inputBox.parentNode.parentNode.removeChild(this._inputBox.parentNode)}catch(c){}a=p.widgets.bookmarks.NLS_new_bookmark;this._label.innerHTML=""===this._inputBox.value?a:this._inputBox.value;b=m(".esriBookmarkLabel",this.bookmarkDomNode);g.forEach(this.bookmarks,function(a,c){a&&(a.name=b[c].innerHTML)});this._inputBox=null;this.onEdit()},_avatarCreator:function(a,b){var c=l.create("div");c.id=dojo.dnd.getUniqueId();h.add(c,
"dojoDndItem");"avatar"!==b&&l.place(a,c);return{node:c,data:a,type:"something"}},_onClickHandler:function(a){var b=a.extent;a.extent.declaredClass||(b=new n(a.extent));this.map.setExtent(b);this.onClick()},toJson:function(){var a=[];g.forEach(this.bookmarks,function(b){b&&a.push(b.toJson())});return a}});x("extend-esri")&&e.setObject("dijit.Bookmarks",q,C);return q});