//>>built
define("esri/dijit/metadata/nls/et/i18nBase",{general:{cancel:"T\u00fchista",close:"Sulge",none:"Puudub",ok:"OK",other:"Muu",stamp:"Tempel",now:"Praegu",choose:"Vali \u00fcks:"},editor:{noMetadata:"Selle \u00fcksuse metaandmed puuduvad.",xmlViewOnly:"Redaktor ei toeta selle \u00fcksusega seotud metaandmete t\u00fc\u00fcpi. Metaandmed peavad olema ArcGIS-i vormingus.",editorDialog:{caption:"Metaandmed",captionPattern:"Metaandmed - {title}"},primaryToolbar:{view:"Vaatamine",viewXml:"Kuva XML",edit:"Muuda",
initializing:"Laadimine...",startingEditor:"Redaktori k\u00e4ivitamine...",loadingDocument:"Dokumendi laadimine...",updatingDocument:"Dokumendi uuendamine...",generatingView:"Vaate genereerimine...",errors:{errorGeneratingView:"Vaate genereerimisel tekkis viga.",errorLoadingDocument:"Dokumendi laadimisel tekkis viga."}},changesNotSaved:{prompt:"Teie dokumendis on salvestamata muudatusi.",dialogTitle:"Sule metaandmete redaktor",closeButton:"Sulge"},download:{caption:"Laadi alla",dialogTitle:"Laadi alla",
prompt:"Faili allalaadimiseks kl\u00f5psake siin."},load:{caption:"Avatud",dialogTitle:"Avatud",typeTab:"Uus dokument",fileTab:"Ava fail",templateTab:"Mall",itemTab:"Teie \u00fcksus",filePrompt:"Valige kohalik ArcGIS-i metaandmete XML-fail. Metaandmed peavad olema ArcGIS-i vormingus.",templatePrompt:"Metaandmete loomine",pullItem:"M\u00e4\u00e4rake metaandmed \u00fcksuse detailide kasutades.",importWarning:"Valitud fail ei ole ArcGIS-i vormingus. \u00dcles laaditud metaandmed peavad olema ArcGIS-i vormingus.",
loading:"Laadimine...",noMetadata:"Selle \u00fcksuse metaandmeid saab luua, valides \u00fche j\u00e4rgmistest valikutest.",unrecognizedMetadata:"Redaktor ei toeta selle \u00fcksusega seotud metaandmete t\u00fc\u00fcpi. Toetatud metaandmeid saab luua, valides \u00fche j\u00e4rgmistest valikutest.",errorLoading:"Laadimisel ilmnes viga.",warnings:{badFile:"Valitud faili ei saanud laadida.",notAnXml:"Valitud fail pole XML-fail.",notSupported:"Seda failit\u00fc\u00fcpi ei toetata."}},save:{caption:"Salvesta",
dialogTitle:"Metaandmete salvestamine",working:"Metaandmete salvestamine...",errorSaving:"Ilmnes viga, teie metaandmeid ei salvestatud.",saveDialog:{pushCaption:"Rakenda muudatused \u00fcksusele"}},saveAndClose:{caption:"Salvesta ja sulge"},saveDraft:{caption:"Salvesta kohalik koopia",dialogTitle:"Salvesta kohalik koopia"},validate:{caption:"Valideeri",dialogTitle:"Valideerimine",docIsValid:"Dokument on kehtiv."},del:{caption:"Kustuta",dialogTitle:"Kustuta metaandmed",prompt:"Kas soovid need metaandmed kindlasti kustutada?",
working:"Metaandmete kustutamine...",errorDeleting:"Ilmnes viga, teie metaandmeid ei kustutatud."},transform:{caption:"Teisenda",dialogTitle:"Teisenda:",prompt:"",working:"Teisendamine...",errorTransforming:"Dokumendi teisendamisel ilmnes viga."},errorDialog:{dialogTitle:"Seal oli viga"}},arcgis:{portal:{metadataButton:{caption:"Metaandmed"}}},calendar:{button:"Kalender...",title:"Kalender"},geoExtent:{button:"M\u00e4\u00e4ra geograafiline ulatus",title:"Geograafiline ulatus",navigate:"Navigeeri",
draw:"Joonista ristk\u00fclik",drawHint:"Alustamiseks hoia all ja l\u00f5petamiseks vabasta."},hints:{date:"(yyyy v\u00f5i yyyy-mm v\u00f5i yyyy-mm-dd)",dateTime:"(yyyy-mm-ddThh:mm:ss.sss[+-]hh:mm)",dateOrDateTime:"(yyyy v\u00f5i yyyy-mm v\u00f5i yyyy-mm-dd v\u00f5i yyyy-mm-ddThh:mm:ss.sss[+-]hh:mm)",delimitedTextArea:"(eraldamiseks kasuta koma v\u00f5i reapiiri)",fgdcDate:"(yyyy v\u00f5i yyyy-mm v\u00f5i yyyy-mm-dd)",fgdcTime:"(hh:mm:ss.sss[+-]hh:mm)",integer:"(sisesta t\u00e4isarv)",latitude:"(k\u00fcmnendikkraadid)",
longitude:"(k\u00fcmnendikkraadid)",number:"(sisesta number)",numberGreaterThanZero:"(sisesta number \x3e 0)"},isoTopicCategoryCode:{caption:"Teemakategooria",boundaries:"Administratiiv- ja poliitilised piirid",farming:"P\u00f5llumajandus ja loomakasvatus",climatologyMeteorologyAtmosphere:"Atmosf\u00e4\u00e4r ja kliima",biota:"Bioloogia ja \u00f6koloogia",economy:"\u00c4ri ja majandus",planningCadastre:"Katastriandmed",society:"Kultuur, \u00fchiskond ja demograafia",elevation:"K\u00f5rgus ja tuletatud tooted",
environment:"Keskkond ja loodushoid",structure:"Omadused ja struktuurid",geoscientificInformation:"Geoloogiline ja geof\u00fc\u00fcsiline",health:"Tervishoid ja haigused",imageryBaseMapsEarthCover:"Satelliit- ja aluskaardid",inlandWaters:"Siseveeressursid",location:"Asukohad ja geodeetilised v\u00f5rgud",intelligenceMilitary:"S\u00f5jaline",oceans:"Ookeanid ja suudmed",transportation:"Transpordiv\u00f5rgustikud",utilitiesCommunication:"Tehnoettev\u00f5tted"},multiplicity:{moveElementDown:"Vii jaotis allapoole",
moveElementUp:"Vii jaotis \u00fclespoole",removeElement:"Eemalda jaotis",repeatElement:"Korda jaotist"},optionalNode:{switchTip:"Kaasa see jaotis v\u00f5i j\u00e4ta v\u00e4lja"},serviceTypes:{featureService:"Objektiteenus",mapService:"Kaarditeenus",imageService:"Pilditeenus",wms:"WMS",wfs:"WFS",wcs:"WCS"},validation:{pattern:"{label} - {message}",patternWithHint:"{label} - {message} {hint}",ok:"OK",empty:"V\u00e4\u00e4rtus on n\u00f5utav.",date:"V\u00e4\u00e4rtus peab olema kuup\u00e4ev.",integer:"V\u00e4\u00e4rtus peab olema t\u00e4isarv.",
number:"V\u00e4\u00e4rtus peab olema arv.",other:"Vigane v\u00e4\u00e4rtus"},validationPane:{clearMessages:"T\u00fchjenda teated",prompt:"(kl\u00f5psake iga allolevat s\u00f5numit ja sisestage m\u00e4\u00e4ratud v\u00e4ljale vajalik teave)"}});